### ISSUE TITLE
What authors to include

### ISSUE THREAD

**Issue by peterdesmet** [inbo/mica-occurrences#20]
Here's a comparison between the Agouti project contributors and current [dataset authors](https://ipt.inbo.be/resource?r=mica-agouti-occurrences#anchor-contacts) for _MICA - Muskrat and coypu camera trap observations in Belgium, the Netherlands and Germany_.

@EmmaCartuyvels1, should we include all contributors as authors? And should Kristof, Sander and Dimi become Agouti project contributors?

person | agouti contributor | dataset author
--- | --- | ---
Emma Cartuyvels | x | x
Tim Adriaens | x | x
Kristof Baert | | x
Dimitri Brosens | | x
Gust Boiten | x | 
Jim Casaer | x | x
Abel De Boer | x |
Sander Devisscher | | x 
Dennis Donckers | x | x
Silke Dupont | x | 
Heiko Fritz | x | x
Lilja Fromme | x | 
Friederike Gethöffer | x | 
Frank Huysentruyt | x | x
Leo Kehl | x | 
Liam Letheren | x | 
Lydia Liebgott | x | 
Yorick Liefting | x | 
Jan Lodewijkx | x | x
Claudia Maistrelli | x | x
Björn Matthies | x | 
Kelly Meijvisch | x | 
Dolf Moerkens | x | 
Axel Neukermans | x | x
Kurt Schamp | x | 
Dan Slootmaekers | x | x
Danny Van der beeck | x | x
Peter Desmet | x | x

**Comment by EmmaCartuyvels1** [comment]
Hi Peter,

I think it would be best to include all contributors as authors, one problem I notice is that past contributors (that did a lot of annotation but are not currently working on the project, e.g. Brecht Neukermans) are not on this list and I do think they should be included as well. 

For Kristof and Sander, I will ask them if they want to be included and if so that they annotate a few sequences. Dimi you can include, since I assume he helped with the data publication?

**Comment by peterdesmet** [comment]
Ok, so let's include all. You'll invite Kristof and Sander to the Agouti project? I'll manually add Dimi, Brecht ... any other past contributors?
